class SP_Static_Wardrobe : SP_ItemBase_Static{}
class SP_Static_Locker_Closed : SP_ItemBase_Static{}
class SP_Static_Locker_Closed_Blue : SP_ItemBase_Static{}
class SP_Static_SeaChest extends SP_ItemBase_Static{}
class SP_Static_SeaChest_Without_Attachements : SP_ItemBase_Static{};
class SP_StaticObj_Misc_WoodenCrate : SP_ItemBase_Static{};
class SP_StaticObj_Furniture_shelfs_small extends SP_ItemBase_Static{}
class SP_StaticObj_Furniture_office_table_a : SP_ItemBase_Static{};
class SP_StaticObj_Furniture_fridge : SP_ItemBase_Static{};
class SP_StaticObj_Furniture_vending_machine : SP_ItemBase_Static{};
class SP_StaticObj_Furniture_Box_C : SP_ItemBase_Static{};
class SP_StaticObj_AmmoBox : SP_ItemBase_Static{};
class SP_StaticObj_Case_Cans_B : SP_ItemBase_Static{};
class SP_StaticObj_Furniture_metalcrate : SP_ItemBase_Static{};
class SP_StaticObj_Furniture_class_case_a_closed : SP_ItemBase_Static{};